
/*
DECLARE @ENV AS NVARCHAR(50)
SET @ENV=		--?Ы??w???Ʈw????
*/

-- ?Ȥ????ƥh?ѧO??
UPDATE
	CLIENT
SET
	CPY_NAME=CASE WHEN CPY_TYPE='PERSON' THEN CONCAT('?Ȥ?',ROWSEQ) ELSE CPY_NAME END,
	CPY_REGISTERID=CASE WHEN CPY_TYPE='PERSON' THEN CONCAT('A',ROWSEQ,RIGHT('123456789'+ RTRIM(ROWSEQ), 9-LEN(ROWSEQ))) ELSE CPY_REGISTERID END,
	CPY_ADDRESS=CASE WHEN CPY_TYPE='PERSON' THEN CONCAT(CPY_ADDRESS,ROWSEQ) ELSE CPY_ADDRESS END,
	CPY_EMAIL=CONCAT(ROWSEQ,'@EMAIL'),
	CPY_FO_TEL=SUBSTRING(CPY_FO_TEL,1,2)+'888888'+SUBSTRING(CPY_FO_TEL,9,LEN(CPY_FO_TEL)),
	CPY_BO_CONTACT_1=CONCAT('?p???H1',ROWSEQ),
	CPY_BO_CONTACT_2=CONCAT('?p???H2',ROWSEQ),
	CPY_BO_TEL_1=SUBSTRING(CPY_BO_TEL_1,1,2)+'888888'+SUBSTRING(CPY_BO_TEL_1,9,LEN(CPY_FO_TEL)),
	CPY_BO_TEL_2=SUBSTRING(CPY_BO_TEL_2,1,2)+'888888'+SUBSTRING(CPY_BO_TEL_2,9,LEN(CPY_FO_TEL)),
	CPY_ACC_TW=CASE WHEN CPY_TYPE='PERSON' THEN '88888888'+SUBSTRING(CPY_ACC_TW,9,LEN(CPY_ACC_TW)) ELSE CPY_ACC_TW END,
	CPY_ACC_TW_NAME=CASE WHEN CPY_TYPE='PERSON' THEN CONCAT('?Ȥ?',ROWSEQ) ELSE CPY_ACC_TW_NAME END,
	CPY_ACC_TW_1=CASE WHEN CPY_TYPE='PERSON' THEN '888888881'+SUBSTRING(CPY_ACC_TW_1,9,LEN(CPY_ACC_TW_1)) ELSE CPY_ACC_TW_1 END,
	CPY_ACC_TW_NAME_1=CASE WHEN CPY_TYPE='PERSON' THEN CONCAT('?Ȥ?1',ROWSEQ) ELSE CPY_ACC_TW_NAME_1 END,
	CPY_ACC_TW_2=CASE WHEN CPY_TYPE='PERSON' THEN '888888882'+SUBSTRING(CPY_ACC_TW_2,9,LEN(CPY_ACC_TW_2)) ELSE CPY_ACC_TW_2 END,
	CPY_ACC_TW_NAME_2=CASE WHEN CPY_TYPE='PERSON' THEN CONCAT('?Ȥ?2',ROWSEQ) ELSE CPY_ACC_TW_NAME_2 END,
	CPY_ACC_TW_3=CASE WHEN CPY_TYPE='PERSON' THEN '888888883'+SUBSTRING(CPY_ACC_TW_3,9,LEN(CPY_ACC_TW_3)) ELSE CPY_ACC_TW_3 END,
	CPY_ACC_TW_NAME_3=CASE WHEN CPY_TYPE='PERSON' THEN CONCAT('?Ȥ?3',ROWSEQ) ELSE CPY_ACC_TW_NAME_3 END,
	CPY_FO_TRADER_1=SUBSTRING(CPY_FO_TRADER_1,1,1)+'???u1',
	CPY_FO_TRADER_2=SUBSTRING(CPY_FO_TRADER_2,1,1)+'???u2',
	CPY_SALES=SUBSTRING(CPY_SALES,1,1)+'???u',
	CPY_SALES_BR=SUBSTRING(CPY_SALES_BR,1,1)+'???u'
FROM
	CLIENT
WHERE
	@ENV IN ('UAT','SIT')

-- ?Ȥ????ƥh?ѧO??
UPDATE
	PARTY
SET
	CPY_NAME=CASE WHEN CPY_TYPE LIKE 'PERSON%' THEN CONCAT('?Ȥ?',ROWSEQ) ELSE CPY_NAME END,
	CPY_REGISTERID=CASE WHEN CPY_TYPE LIKE 'PERSON%' THEN CONCAT('A',ROWSEQ,RIGHT('123456789'+ RTRIM(ROWSEQ), 9-LEN(ROWSEQ))) ELSE CPY_REGISTERID END,
	CPY_ADDRESS=CASE WHEN CPY_TYPE LIKE 'PERSON%' THEN CONCAT(CPY_ADDRESS,ROWSEQ) ELSE CPY_ADDRESS END,
	CPY_EMAIL=CONCAT(ROWSEQ,'@EMAIL'),
	CPY_SALES=SUBSTRING(CPY_SALES,1,1)+'???u',
	CPY_SALES_BR=SUBSTRING(CPY_SALES_BR,1,1)+'???u'
FROM
	PARTY
WHERE
	@ENV IN ('UAT','SIT')

-- ?Ȥ??b?????ƥh?ѧO??
UPDATE
	PARTY_ACC
SET
	ACC_NUM=CONCAT(LEFT(ACC.ACC_NUM,4),ACC.ROWSEQ,SUBSTRING(ACC.ACC_NUM,9,LEN(ACC.ACC_NUM))),
	ACC_NAME=CONCAT('?Ȥ?',ACC.ROWSEQ)
FROM
	PARTY CP
	JOIN PARTY_ACC ACC ON ACC.ACC_PTY_NBR=CP.CPY_NBR AND CP.CPY_TYPE LIKE 'PERSON%'
WHERE
	@ENV IN ('UAT','SIT')

-- ?Ȥ??p???H???ƥh?ѧO??
UPDATE
	PARTY_CT
SET
	CT_NAME=CONCAT('?p???H',ROWSEQ),
	CT_TEL=SUBSTRING(CT_TEL,1,4)+'8888'+SUBSTRING(CT_TEL,9,LEN(CT_TEL)),
	CT_FAX=SUBSTRING(CT_FAX,1,4)+'8888'+SUBSTRING(CT_FAX,9,LEN(CT_FAX))
FROM
	PARTY_CT
WHERE
	@ENV IN ('UAT','SIT')
	
-- ?????D?}?o?H????e-mail
DELETE
	GROUPUSER
FROM
(
	SELECT
		GRPU_USERID
	FROM
		GROUPUSER GU
	WHERE
		GU.GRPU_ID='M-CMONEY'
	AND NOT EXISTS(
		SELECT 0 FROM GROUPUSER WHERE GRPU_ID='SYSAPTEAM' AND GRPU_USERID=GU.GRPU_USERID
	)
) X
WHERE
	GROUPUSER.GRPU_USERID=X.GRPU_USERID
AND GRPU_ID='M-CMONEY'
AND @ENV='SIT'

--??DB?n?J
UPDATE USERS SET USR_CHECK='DB' WHERE @ENV IN ('UAT','SIT')

--???T???????v??
IF @ENV IN ('UAT','SIT')
BEGIN
	DELETE FROM GROUPFCN WHERE GRP_ID IN ('SYSAPTEAM','SYSACMNGR','SYSAPTEAM')
	INSERT INTO GROUPFCN (GRP_ID,GRP_FCNID,GRP_TYPE)
	SELECT 'SYSAPTEAM',FCN_ID,'WRITE' FROM FUNCTIONS
	UNION SELECT 'SYSACMNGR',FCN_ID,'WRITE' FROM FUNCTIONS WHERE FCN_ID IN (1,2,37)
	UNION SELECT 'SYSAPTEAM',FCN_ID,'WRITE' FROM FUNCTIONS WHERE FCN_ID IN (1,2,37)
	UPDATE USERS SET USR_GROUPID='SYSAPTEAM' WHERE USR_USERID='Z00036622'
END

